### PR TITLE
Fix deletion of all occurences of a node

### LINKED ISSUE #313: Unable to delete all occurrences of a node
## Describe the bug
When trying to remove a node and choose the "Delete all occurrences of foo" delete option, the following error is displayed.

Bildschirmfoto 2021-11-25 um 17 28 36

## To Reproduce
Provide a link to a live example, or an unambiguous set of steps to reproduce this issue. Include configuration, logs, etc. to reproduce, if relevant.

1. Create a new process "Test"
2. Add a new node `foo` of type host
3. Try to remove `foo` and choose `Delete all occurrences of "foo"` as a delete option

**Result:** Failed! Error message see above!

### PR DESCRIPTION
**Pull request by raviks789**
In case the node is not a BP node, we simply have to remove all occurrences of the node.

fixes #313

### CODE REVIEW

File: library/Businessprocess/Modification/NodeRemoveAction.php [hunk 1]
```diff
@@ -65,15 +65,19 @@ public function applyTo(BpConfig $config)
...
-            $oldDisplay = $config->getBpNode($name)->getDisplay();
-            $config->removeNode($name);
-            if ($config->getMetadata()->isManuallyOrdered()) {
-                foreach ($config->getRootNodes() as $_ => $node) {
-                    $nodeDisplay = $node->getDisplay();
-                    if ($nodeDisplay > $oldDisplay) {
-                        $node->setDisplay($node->getDisplay() - 1);
-                    } elseif ($nodeDisplay === $oldDisplay) {
-                        break;  // Stop immediately to not make things worse ;)
+            if (! $config->hasBpNode($name)) {
```
Comment (nilmerg) [inline library/Businessprocess/Modification/NodeRemoveAction.php:68]: I wonder why that would be the case. I mean, a node without a parent must be a process node (root node), so if `hasBpNode()` returns false, is there actually a node at all? Does a `! $config->hasNode($name)` then suffice? Removal then is of course unnecessary.

**Review by nilmerg — APPROVED** [review]
