### PR TITLE
Fix storing of business process with `Description` having new lines

### LINKED ISSUE #311: Newlines in description break the BP configuration
## Describe the bug
The frontend allows to add a description of a business process, with a multiline textarea field. Adding a new line actually breaks the configuration

## To Reproduce

1. Create a BP 
2. Fill the description field with at least 1 new line
3. Save the configuration
4. A error message appears

## Expected behavior
The business process configuration is supposed to be written correctly, but is corrupt. 

## Your Environment
Include as many relevant details about the environment you experienced the problem in

* Icinga Web 2 version and modules (System - About): 2.8.5 (icingaweb2-module-businessprocess 2.3.0 )
* Web browser used: Chrome 
* Icinga 2 version used (`icinga2 --version`):  2.11.9
* PHP version used (`php --version`): 7.3
* Server operating system and version: CentOS 7.9

### PR DESCRIPTION
**Pull request by raviks789**
The `LegacyConfigRenderer::renderHeader()` should render new lines in the `Description` field as comments.

This fix avoids the occurrence of future issues due to new lines in `Description` field when adding or modifying the
business processes.

fixes #311

### CODE REVIEW

File: library/Businessprocess/Storage/LegacyConfigParser.php [hunk 1]
```diff
@@ -11,6 +11,7 @@
 
 class LegacyConfigParser
 {
+    protected static $prevKey;
```
Comment (nilmerg) [inline library/Businessprocess/Storage/LegacyConfigParser.php:14]: doc pls and a line break

**Review by nilmerg — APPROVED** [review]
