### PR TITLE
DeleteNodeForm: Remove stateoverrides of node by removing node

### LINKED ISSUE #357: State overrides of the removed host/service node are still present in the config file
## Describe the bug
When a host/service node with state overrides is removed, the state overrides for it are still present in the config file.

## To Reproduce
1. Add a host/service node with state overrides.
2. Remove the node.
3. Take a look at the config file.

## Expected behavior
State overrides should also be removed.

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #357

### CODE REVIEW

**Review by nilmerg — COMMENTED** [review]
Have you checked whether it makes sense to perform the override cleanup in `NodeRemoveAction`? This way, the override cleanup wouldn't be necessary to consider in new implementations, like in #355

**Review by nilmerg — CHANGES_REQUESTED** [review]

File: library/Businessprocess/Modification/NodeRemoveAction.php [hunk 1]
```diff
@@ -91,4 +99,28 @@ public function applyTo(BpConfig $config)
...
+     * Update state overrides
+     *
+     * @param Node $node
+     * @param BpNode|null $nodeParent
+     *
+     * @return void
+     */
+    private function updateStateOverrides(Node $node, ?BpNode $nodeParent): void
+    {
+        $parents = null;
```
Comment (nilmerg) [inline library/Businessprocess/Modification/NodeRemoveAction.php:113]: This should be a list, not null.

File: library/Businessprocess/Modification/NodeRemoveAction.php [hunk 2]
```diff
@@ -91,4 +99,28 @@ public function applyTo(BpConfig $config)
...
+        if ($nodeParent !== null) {
+            $parents[] = $nodeParent;
```
Comment (nilmerg) [inline library/Businessprocess/Modification/NodeRemoveAction.php:115]: Or this should not append but initialize. (`[$nodeParent]`)

**Review by nilmerg — CHANGES_REQUESTED** [review]

**Review by nilmerg — APPROVED** [review]
