### PR TITLE
Show service and host nodes for filtered roles

### LINKED ISSUE #345: IcingaDB - Services in BPs are not shown anymore for filtered roles (missing nodes)
## Describe the bug
Hi all,
I have two different views between the monitoring and the icingadbweb module right now.
Monitoring: When a role has access to a BP, the user can see the whole BP, no matter if the user has access to the several service details or not. When they don't have access to the service details, they get a permission denied info. But they can see the whole status of the BP itself

IcingaDB: The services, which are locked for the role disappear in the business process, too. The user gets the red bar with "X nodes are missing". So the BP is not usable anymore. I have to unlock every service for the roles, what was not necessary in the monitoring module. 

## To Reproduce

1. Create a BP
2. Filter a service for a specific role
3. The service is visible in the BP for the filtered role when using the monitoring module, service details are locked with "no permission"
4. The service is not visible in the BP for the filtered role, when using the Icingadbweb module, user gets "nodes missing"

## Expected behavior
Same view in both monitoring and icingadbweb modules

## Screenshots
image
image

## Your Environment
Ubuntu 20.04.4 lts
Icinga Web 2 Version	2.11.1
PHP Version	7.4.3
icinga/icinga-php-thirdparty	0.11.0
icinga/icinga-php-library	0.9.1
businessprocess		2.4.0	Configure

## Additional context
Module is currently not usable with IcingaDB :(

### PR DESCRIPTION
**Pull request by raviks789**
The service and host nodes must be shown, but clicking on these nodes should show
"Access Denied" page.

fixes #345

### CODE REVIEW

File: application/controllers/HostController.php [hunk 1]
```diff
@@ -44,7 +44,7 @@ public function showAction()
 
             $this->params->add('name', $hostName);
 
-            if ($host !== false) {
```
Comment (lippserd) [inline application/controllers/HostController.php:47]: Are those changes really necessary?

Comment (raviks789) [reply application/controllers/HostController.php:47]: Yes, `$host` or `$service` will be `null` instead of `false` after restriction is applied.

Comment (lippserd) [reply application/controllers/HostController.php:47]: How can it return either `null` or `false`?

Comment (raviks789) [reply application/controllers/HostController.php:47]: I think there is a misunderstanding here. The query returns either the row as object or null (in case there is no result). So after the restriction the object will be null.

Comment (lippserd) [reply application/controllers/HostController.php:47]: So the check should be `!== null`, because `!== false` was never correct.

Comment (raviks789) [reply application/controllers/HostController.php:47]: Makes sense. I will make the changes.

**Review by nilmerg — APPROVED** [review]
