### PR TITLE
ProcessCommand: Fix false positive condition for `ServiceNode`

### LINKED ISSUE #440: CLI command: Don't throw error on empty nodes
## Describe the bug
When running the check command against a process with an empty node the check writes an error message into the check output but keeps on working otherwise:
```
ERROR: ErrorException in /usr/share/icingaweb2/modules/businessprocess/application/clicommands/ProcessCommand.php:198 with message: Undefined offset: 128
```

## To Reproduce
Have a process with an empty node:
image
## Expected behavior
Don't throw error on empty nodes.

## Your Environment
Icinga Web 2 2.11.3
PHP 7.3.33
Module version 2.4.1, but as the code is the same in 2.5.0 I guess an update wouldn't solve this.

### PR DESCRIPTION
**Pull request by sukhwinder33445**
fixes #440

### CODE REVIEW

File: application/clicommands/ProcessCommand.php [hunk 1]
```diff
@@ -192,9 +193,10 @@ protected function renderProblemTree($tree, $useColors = false, $depth = 0, BpNo
             $node = $subtree['node'];
             $state = $parent !== null ? $parent->getChildState($node) : $node->getState();
 
+            $colors = [];
             if ($node instanceof HostNode) {
                 $colors = $this->hostColors[$state];
-            } else {
+            } elseif ($node instanceof ServiceNode) {
                 $colors = $this->serviceColors[$state];
             }
```
Comment (raviks789) [inline application/clicommands/ProcessCommand.php:202]: I think after this if-elseif, there is an if block which apply colors if the `--colors` flag is used in the process command. I think there, you would also have to check if the `$colors` is not an empty array.

**Review by raviks789 — APPROVED** [review]

**Review by nilmerg — APPROVED** [review]
