### PR TITLE
Do not break sidebar if processes cannot be loaded

### LINKED ISSUE #466: Disabling both backends breaks Icinga Web UI
## Describe the bug
This module relies on either the `icingadb` or the `monitoring` module.

When neither module is enabled but the `businessprocess` module itself is enabled, Icinga Web's UI breaks.

Navigation is no longer possible (using simple click navigation, URL paths can be used if the user knows them).

If disabling both possible backends, the UI breaks immediately.

Image

Here I can still fix it be reenabling either backend.

Once I navigate away from this URL path, I'm out of luck.

Image

Here no more useful clickable surfaces are available.

> Screenshot using Vimium browser extension to highlight every button I could click

Image

The only solution I found (apart from knowing the URL to toggle either backend) is to use `icingacli module enable icingadb` (in my case).

Not everyone - especially in production - will be able to access the CLI as well!

EDIT:  
I've just noticed that I can click `modules` on the landing page, bringing me back to the modules screen. From there I can enable either backend.  
Regardless of that, I still would not expect the UI to break this way.

## To Reproduce

1. Install and enable (optional IcingaDB-Web and) BusinessProcess
2. Disable all possible backends (`icingadb` and `monitoring`)
3. Observe the error

## Expected behavior
I would expect Icinga Web to work properly and the Business Process module to fail in a non-breaking manner (e.g. red banner with text).

## Environment

Ubuntu 22.04

Icinga Web 2 Version            2.12.4
Git commit                      219b11789beb0484b7993fa9ea838edd211ca5b2
PHP Version                     8.1.2-1ubuntu2.21
Git commit date                 2025-03-26

Loaded Libraries
icinga/icinga-php-thirdparty    0.12.1
icinga/icinga-php-library       0.14.2

Loaded Modules
businessprocess                 2.5.1 (via git checkout)
director                        1.11.5
icingadb                        1.1.3
incubator                       0.22.0

### PR DESCRIPTION
**Pull request by nilmerg**
fixes #466

### CODE REVIEW

File: library/Businessprocess/Web/Navigation/Renderer/ProcessProblemsBadge.php [hunk 1]
```diff
@@ -20,22 +22,26 @@ class ProcessProblemsBadge extends BadgeNavigationItemRenderer
...
+            } catch (Throwable $e) {
+                Logger::error('Failed to load business process "%s": %s', $this->getBpConfigName(), $e);
             }
 
             $this->count = $count;
-            $this->setState(self::STATE_CRITICAL);
-        }
 
-        if ($count) {
+            $this->setState(self::STATE_CRITICAL);
```
Comment (sukhwinder33445) [inline library/Businessprocess/Web/Navigation/Renderer/ProcessProblemsBadge.php:44]: These changes have no effect,  `IcingaDbState::apply($bp)` or `MonitoringState::apply($bp)`

Comment (sukhwinder33445) [reply library/Businessprocess/Web/Navigation/Renderer/ProcessProblemsBadge.php:44]: ### But there is another bug (OR Operator):
Nodes are OK, but a critical badge is rendered.
Screenshot 2025-06-30 at 15 18 04

A Node has WARNING state, but a critical badge is rendered.
Screenshot 2025-06-30 at 15 02 36


Because a hard-coded state is set with: `$this->setState(self::STATE_CRITICAL);`

Comment (slalomsk8er) [reply library/Businessprocess/Web/Navigation/Renderer/ProcessProblemsBadge.php:44]: this looks related to https://github.com/Icinga/icingaweb2-module-businessprocess/issues/365

Comment (nilmerg) [reply library/Businessprocess/Web/Navigation/Renderer/ProcessProblemsBadge.php:47]: Both classes are used to extend menu entries. As such, they have to make sure the menu doesn't break. To do so, both were adjusted to wrap the error prone code in a try-catch block.

Not sure though, how you got a badge for only OK nodes. I don't get one.

Comment (nilmerg) [reply library/Businessprocess/Web/Navigation/Renderer/ProcessProblemsBadge.php:47]: Now I am sure. While the menu breaks if neither monitoring nor icingadb are enabled, the views work fine as long as monitoring is _installed_. The views autoload monitoring if disabled. I verified that this isn't required if a user has no permission for monitoring. So, it's rather weird that it exists, but I keep it for now since removing it would be a potential breaking change.

**Review by sukhwinder33445 — APPROVED** [review]
