### PR TITLE
Fix problems with empty nodes

### LINKED ISSUE #225: Newly created BP and root node shows count 1 and purple unknown since 1970-01
## Expected Behavior

Root nodes should show `0` as count, and the unknown is kind of irritating ... better use "pending" or similar.

## Current Behavior

Empty root nodes show a count of one, and once opened they are unknown since 1970-01.

Screen Shot 2019-03-22 at 15 49 43
Screen Shot 2019-03-22 at 15 49 03
Screen Shot 2019-03-22 at 15 48 39

## Possible Solution

Sorry, I don't know the code (yet).

## Steps to Reproduce (for bugs)

1. Create a new BP, "databases"
2. Create a new root node as suggested, "production"
3. See the greyed out node, with count 1
4. Open it, and see the breadcrumb being purple unknown since 1970-01

## Context

Writing a blog post and doing everything with the UI, and not vim. 

## Your Environment

* Module version (System - About): 2.2.0
* Icinga Web 2 version and modules (System - About): 2.6.2, a487f83f99e440bc71e268725a31943d9e29ea75

```
Name        : icingaweb2
Arch        : noarch
Version     : 2.6.2.24.ga487f83
Release     : 0.2019.02.21+1.el7.icinga
Size        : 6.9 M
Repo        : installed
From repo   : icinga-snapshot-builds
Summary     : Icinga Web 2
URL         : https://icinga.com
License     : GPLv2+ and MIT and BSD
Description : Icinga Web 2
```

* Icinga 2 version (`icinga2 --version`): v2.10.2-257-g856d3a1
* Operating System and version: CentOS 7
* Webserver, PHP versions: apache 2.4, PHP 7.1 from SCL

### LINKED ISSUE #270: Problems with imported nodes that are empty
## Describe the bug

If an imported node is empty or if it is deleted at a later time then there is a problem with 
`sourceURL()`.  This results in an exception **'Trying to access a missing business process node <$name>'**.

### Empty Node

1. create a new business process with some name (Test).
2. add an empty node to this business process (Test-process).
3. create one more business process (Test1).
4. add a node to this process by importing business process Test.

### Deleted Node

1. create a new business process with some name (Test).
2. add an empty node to this business process (Test-process).
3. create one more business process (Test1).
4. add a node to this process by importing business process *Test*.
5. delete the node *Test-process* in the business process *Test*.

## Your Environment

icingaweb2 - 2.6.3-1.stretch, icingaweb2-module-businessprocess 2.1.0.

### PR DESCRIPTION
**Pull request by raviks789**
fixes #225 
fixes #270

### CODE REVIEW

File: library/Businessprocess/BpNode.php [hunk 1]
```diff
@@ -73,9 +74,6 @@ public function getStateSummary()
                     $this->counters[$state]++;
                 }
             }
-            if (! $this->hasChildren()) {
```
Comment (lippserd) [inline library/Businessprocess/BpNode.php]: This change should be single commit.

File: library/Businessprocess/BpNode.php [hunk 2]
```diff
@@ -355,8 +353,7 @@ public function reCalculateState()
 
         if (!$this->hasChildren()) {
             // TODO: delegate this to operators, should mostly fail
-            $this->setState(self::ICINGA_UNKNOWN);
-            $this->setMissing();
+            $this->setState(self::NODE_EMPTY);
```
Comment (lippserd) [inline library/Businessprocess/BpNode.php]: This change should be a single commit.

File: library/Businessprocess/Node.php [hunk 3]
```diff
@@ -21,6 +21,7 @@ abstract class Node
     const ICINGA_DOWN        = 1;
     const ICINGA_UNREACHABLE = 2;
     const ICINGA_PENDING     = 99;
+    const NODE_EMPTY         = 128;
```
Comment (lippserd) [inline library/Businessprocess/Node.php]: Introducing the node empty "state" should be a single commit.

File: public/css/module.less [hunk 4]
```diff
@@ -519,6 +519,7 @@ td > a > .badges {
     > .pending             { background-color: @colorPending;           > a { text-shadow: 0 0 1px mix(#000, @colorPending, 40%); }}
     > .missing             { background-color: @gray-light;             > a { text-shadow: 0 0 1px @gray }}
     > .addnew              { background-color: @icinga-blue;            > a { text-shadow: 0 0 1px mix(#000, @icinga-blue, 40%); }}
+    > .empty               { background-color: @gray-light;             > a { text-shadow: 0 0 1px @gray }}
```
Comment (lippserd) [inline public/css/module.less]: The style changes should be a single commit.
